language: c++
compiler:
- clang++
- g++
sudo: false
# cache: ccache

# blocklist
# branches:
#   except:
#   - development-psa
#   - coverity_scan

script:
- tests/scripts/basic_tests.sh
# after_failure:
# - tests/scripts/travis-log-failure.sh
# env:
#   global:
#     secure: "barHldniAfXyoWOD/vcO+E6/Xm4fmcaUoC9BeKW+LwsHqlDMLvugaJnmLXkSpkbYhVL61Hzf3bo0KPJn88AFc5Rkf8oYHPjH4adMnVXkf3B9ghHCgznqHsAH3choo6tnPxaFgOwOYmLGb382nQxfE5lUdvnM/W/psQjWt66A1+k="
#
addons:
  coverity_scan:
    project:
      name: "asn1codec"
    notification_email: 15605189715@163.com
    build_command_prepend:
    build_command: make
branch_pattern: coverity_scan
